/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DIU.Vista;

import DIU.Modelo.PersonaModelo;
import javax.swing.JInternalFrame;

/**
 *
 * @author Usuario
 */
public class PantallaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    private PersonaModelo persona;

    // Constructor sin parámetros
    public PantallaAdministrador() {
        initComponents();
    }

    // Constructor con parámetro PersonaModelo
    public PantallaAdministrador(PersonaModelo persona) {
        this.persona = persona;
        initComponents();
        lblNombres.setText(persona.getNombres());
        lblApellidos.setText(persona.getApellidos());
    }
    private JInternalFrame ventanaActual = null; // Variable para almacenar la ventana actual

    private void abrirVentana(JInternalFrame nuevaVentana) {
        if (ventanaActual != null) {
            ventanaActual.dispose(); // Cierra la ventana actual
        }
        escritorio.add(nuevaVentana); // Añade la nueva ventana al escritorio
        nuevaVentana.show(); // Muestra la nueva ventana
        ventanaActual = nuevaVentana; // Actualiza la ventana actual
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lblEscudo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPropiedades = new javax.swing.JMenu();
        opLPropiedades = new javax.swing.JMenuItem();
        menuPropietarios = new javax.swing.JMenu();
        opLPropietarios = new javax.swing.JMenuItem();
        menuCuentas = new javax.swing.JMenu();
        opLHistorialPersona = new javax.swing.JMenuItem();
        opLHistorilaDatosPredios = new javax.swing.JMenuItem();
        MenuAdmin = new javax.swing.JMenu();
        opLCerrar = new javax.swing.JMenuItem();
        lblNombres = new javax.swing.JMenu();
        lblApellidos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 204, 204));

        lblEscudo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\NetBeansProjects\\SimuladorImpuestoPredial\\src\\main\\resources\\Imgs\\Escudo2.png")); // NOI18N

        escritorio.setLayer(lblEscudo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(lblEscudo, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEscudo, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPropiedades.setText("Gestión Propiedades");

        opLPropiedades.setText("Propiedades");
        opLPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLPropiedadesActionPerformed(evt);
            }
        });
        menuPropiedades.add(opLPropiedades);

        jMenuBar1.add(menuPropiedades);

        menuPropietarios.setText("Gestión Propietarios");

        opLPropietarios.setText("Propietarios");
        opLPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLPropietariosActionPerformed(evt);
            }
        });
        menuPropietarios.add(opLPropietarios);

        jMenuBar1.add(menuPropietarios);

        menuCuentas.setText("Gestion historial");

        opLHistorialPersona.setText("Historial Persona");
        opLHistorialPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLHistorialPersonaActionPerformed(evt);
            }
        });
        menuCuentas.add(opLHistorialPersona);

        opLHistorilaDatosPredios.setText("Historial Datos Predios");
        opLHistorilaDatosPredios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLHistorilaDatosPrediosActionPerformed(evt);
            }
        });
        menuCuentas.add(opLHistorilaDatosPredios);

        jMenuBar1.add(menuCuentas);

        MenuAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\NetBeansProjects\\SimuladorImpuestoPredial\\src\\main\\resources\\Imgs\\AdministradorImgn.jpg")); // NOI18N

        opLCerrar.setText("Cerrar Sesión");
        opLCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLCerrarActionPerformed(evt);
            }
        });
        MenuAdmin.add(opLCerrar);

        jMenuBar1.add(MenuAdmin);

        lblNombres.setText("jMenu1");
        jMenuBar1.add(lblNombres);

        lblApellidos.setText("jMenu2");
        jMenuBar1.add(lblApellidos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opLPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLPropiedadesActionPerformed
        TablaRegistrarPropiedad Propiedades = new TablaRegistrarPropiedad();
        abrirVentana(Propiedades);
    }//GEN-LAST:event_opLPropiedadesActionPerformed

    private void opLCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLCerrarActionPerformed
        PantallaPrincipal pantallaPrin = new PantallaPrincipal();
        pantallaPrin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_opLCerrarActionPerformed

    private void opLPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLPropietariosActionPerformed
        TablablaRegistrarCiudadanos Propietarios = new TablablaRegistrarCiudadanos();
        abrirVentana(Propietarios);
    }//GEN-LAST:event_opLPropietariosActionPerformed

    private void opLHistorialPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLHistorialPersonaActionPerformed
        TablaHistorialPersona hP = new TablaHistorialPersona();
        abrirVentana(hP);
    }//GEN-LAST:event_opLHistorialPersonaActionPerformed

    private void opLHistorilaDatosPrediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLHistorilaDatosPrediosActionPerformed
        TablaHistoriaDatosPrediales hDP = new TablaHistoriaDatosPrediales();
        abrirVentana(hDP);
    }//GEN-LAST:event_opLHistorilaDatosPrediosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu lblApellidos;
    private javax.swing.JLabel lblEscudo;
    private javax.swing.JMenu lblNombres;
    private javax.swing.JMenu menuCuentas;
    private javax.swing.JMenu menuPropiedades;
    private javax.swing.JMenu menuPropietarios;
    private javax.swing.JMenuItem opLCerrar;
    private javax.swing.JMenuItem opLHistorialPersona;
    private javax.swing.JMenuItem opLHistorilaDatosPredios;
    private javax.swing.JMenuItem opLPropiedades;
    private javax.swing.JMenuItem opLPropietarios;
    // End of variables declaration//GEN-END:variables
}
