/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DIU.Vista;

import DIU.Modelo.PersonaModelo;

/**
 *
 * @author Usuario
 */
public class PantallaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    private PersonaModelo persona;

    // Constructor sin parámetros
    public PantallaAdministrador() {
        initComponents();
    }

    // Constructor con parámetro PersonaModelo
    public PantallaAdministrador(PersonaModelo persona) {
        this.persona = persona;
        initComponents();
        lblNombres.setText(persona.getNombres());
        lblApellidos.setText(persona.getApellidos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPropiedades = new javax.swing.JMenu();
        opLPropiedades = new javax.swing.JMenuItem();
        menuPropietarios = new javax.swing.JMenu();
        opLPropietarios = new javax.swing.JMenuItem();
        menuCuentas = new javax.swing.JMenu();
        MenuAdmin = new javax.swing.JMenu();
        opLCerrar = new javax.swing.JMenuItem();
        lblNombres = new javax.swing.JMenu();
        lblApellidos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1499, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        menuPropiedades.setText("Gestión Propiedades");

        opLPropiedades.setText("Propiedades");
        opLPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLPropiedadesActionPerformed(evt);
            }
        });
        menuPropiedades.add(opLPropiedades);

        jMenuBar1.add(menuPropiedades);

        menuPropietarios.setText("Gestión Propietarios");

        opLPropietarios.setText("Propietarios");
        opLPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLPropietariosActionPerformed(evt);
            }
        });
        menuPropietarios.add(opLPropietarios);

        jMenuBar1.add(menuPropietarios);

        menuCuentas.setText("Cuentas Administrador");
        jMenuBar1.add(menuCuentas);

        MenuAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\NetBeansProjects\\SimuladorImpuestoPredial\\src\\main\\resources\\Imgs\\AdministradorImgn.jpg")); // NOI18N

        opLCerrar.setText("Cerrar Sesión");
        opLCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLCerrarActionPerformed(evt);
            }
        });
        MenuAdmin.add(opLCerrar);

        jMenuBar1.add(MenuAdmin);

        lblNombres.setText("jMenu1");
        jMenuBar1.add(lblNombres);

        lblApellidos.setText("jMenu2");
        jMenuBar1.add(lblApellidos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opLPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLPropiedadesActionPerformed
        TablaRegistrarPropiedad Propiedades = new TablaRegistrarPropiedad();
        escritorio.add(Propiedades);
        Propiedades.show();
    }//GEN-LAST:event_opLPropiedadesActionPerformed

    private void opLCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLCerrarActionPerformed
        PantallaPrincipal pantallaPrin = new PantallaPrincipal();
        pantallaPrin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_opLCerrarActionPerformed

    private void opLPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLPropietariosActionPerformed
        TablablaRegistrarCiudadanos Propietarios = new TablablaRegistrarCiudadanos();
        escritorio.add(Propietarios);
        Propietarios.show();
    }//GEN-LAST:event_opLPropietariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu lblApellidos;
    private javax.swing.JMenu lblNombres;
    private javax.swing.JMenu menuCuentas;
    private javax.swing.JMenu menuPropiedades;
    private javax.swing.JMenu menuPropietarios;
    private javax.swing.JMenuItem opLCerrar;
    private javax.swing.JMenuItem opLPropiedades;
    private javax.swing.JMenuItem opLPropietarios;
    // End of variables declaration//GEN-END:variables
}
