/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU.Vista;

import DIU.Modelo.ConsultaPagosModelo;
import DIU.Modelo.DatosPredialesModelo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PantallaConsultaCedula extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaConsultaCedula
     */
    public String cedula, codCastralPred, fecha_ingreso_pago, fecha_vencimiento_pago, descripcion_pago, direccion, sub_total_pago;
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<ConsultaPagosModelo> listaConsultaPagoModelo = new ArrayList<>();
    ArrayList<DatosPredialesModelo> listaDatosPredialesModelo = new ArrayList<>();

    public PantallaConsultaCedula() {
        initComponents();
        setModelo();
    }

    public void setModelo() {
        String[] cabecera = {"Nro.", "COD Castral", "Fecha de ingreso dd/mm/aaaa", "Fecha de vencimiento dd/mm/aaaa",
            "Comentario", "Dirección", "Subtotal"};
        modelo.setColumnIdentifiers(cabecera);
        tblConsultaPredios.setModel(modelo);
    }

    public void setDatosPago(ArrayList<Object[]> datosPago) {
        // Limpiar la tabla antes de agregar nuevos datos
        modelo.setRowCount(0);

        // Agregar los datos a la tabla
        for (Object[] fila : datosPago) {
            modelo.addRow(fila);
        }
    }

    public void setDatosPago(int contador, ArrayList<Object[]> datosPago) {
        // Limpiar la tabla antes de agregar nuevos datos
        modelo.setRowCount(0);

        // Agregar los datos a la tabla
        for (Object[] fila : datosPago) {
            Object[] nuevaFila = new Object[7];
            nuevaFila[0] = contador;
            System.arraycopy(fila, 0, nuevaFila, 1, fila.length);
            modelo.addRow(nuevaFila);
            contador++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        btnVerDqtosPrediales = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultaPredios = new javax.swing.JTable();
        btnCalcularPago = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONSULTA DE PREDIOS");

        lblTitulo.setText("Consulta Predios de:");

        lblCedula.setText("jLabel2");

        btnVerDqtosPrediales.setText("Ver datos prediales");

        btnImprimir.setText("Imprimir");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblConsultaPredios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConsultaPredios);

        btnCalcularPago.setText("Calcular Pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerDqtosPrediales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir)
                        .addGap(394, 394, 394)
                        .addComponent(btnCalcularPago)
                        .addGap(134, 134, 134)
                        .addComponent(btnSalir)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblCedula))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDqtosPrediales)
                    .addComponent(btnImprimir)
                    .addComponent(btnSalir)
                    .addComponent(btnCalcularPago))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        PantallaConsultaPredios pantallaPred = new PantallaConsultaPredios();
        pantallaPred.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularPago;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerDqtosPrediales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblConsultaPredios;
    // End of variables declaration//GEN-END:variables
}
