/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU.Vista;

import DIU.Modelo.PersonaYDatosPredialesModelo;
import DIU.Controlador.PersonaYDatosPredialesControlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class TablaGestionPropiedades extends javax.swing.JInternalFrame {

    ArrayList<PersonaYDatosPredialesModelo> listaPersonayDatosPredialesModelo = new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();

    public TablaGestionPropiedades() {
        initComponents();
        setModelo();
    }

    public void setModelo() {
        String[] cabecera = {"Nro.", "Cédula", "Nombres", "Apellidos", "Correo", "Teléfono", "Edad",
            "Código castral", "Tipo propiedad", "Dirección", "Área total", "Área construcción",
            "Valor de terreno", "Valor de edificación", "Valor comercial"};
        modelo.setColumnIdentifiers(cabecera);
        tblPropiedadPro.setModel(modelo);
    }

    private void setDatos() {
        // ESTRUCTURA INFORMACIÓN TABLA
        Object[] datosFilaPersonaYDatosPrediales = new Object[modelo.getColumnCount()];
        int contador = 1;
        for (PersonaYDatosPredialesModelo datos : listaPersonayDatosPredialesModelo) {
            datosFilaPersonaYDatosPrediales[0] = contador;
            datosFilaPersonaYDatosPrediales[1] = datos.getCedula();
            datosFilaPersonaYDatosPrediales[2] = datos.getNombres();
            datosFilaPersonaYDatosPrediales[3] = datos.getApellidos();
            datosFilaPersonaYDatosPrediales[4] = datos.getCorreo();
            datosFilaPersonaYDatosPrediales[5] = datos.getTelefono();
            datosFilaPersonaYDatosPrediales[6] = datos.getEdad();
            datosFilaPersonaYDatosPrediales[7] = datos.getCodCastralPred();
            datosFilaPersonaYDatosPrediales[8] = datos.getTipoPred();
            datosFilaPersonaYDatosPrediales[9] = datos.getDireccionPropie();
            datosFilaPersonaYDatosPrediales[10] = datos.getAreaTotalPred();
            datosFilaPersonaYDatosPrediales[11] = datos.getAreaConstruccionPred();
            datosFilaPersonaYDatosPrediales[12] = datos.getValorTerrenoPred();
            datosFilaPersonaYDatosPrediales[13] = datos.getValorEdificacionPred();
            datosFilaPersonaYDatosPrediales[14] = datos.getValorComercialPred();
            modelo.addRow(datosFilaPersonaYDatosPrediales);

            contador++;
        }
        tblPropiedadPro.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        lblTipoPro = new javax.swing.JLabel();
        rbtnUrbano = new javax.swing.JRadioButton();
        rbtnRural = new javax.swing.JRadioButton();
        lblDireccion = new javax.swing.JLabel();
        txtValorComercial = new javax.swing.JTextField();
        lblValorComercial = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblValorEdificacion = new javax.swing.JLabel();
        txtValorEdificacion = new javax.swing.JTextField();
        lblAreatotal = new javax.swing.JLabel();
        txtAreaTotal = new javax.swing.JTextField();
        lblAreaConstruccion = new javax.swing.JLabel();
        txtAreaConstruccion = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblCodCastral = new javax.swing.JLabel();
        lblValorTerreno = new javax.swing.JLabel();
        txtValorTerreno = new javax.swing.JTextField();
        txtCodCastral = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPropiedadPro = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión de propiedades");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese los siguietes campos del propietario y datos predios"));

        lblNombres.setText("Nombres:");

        lblApellidos.setText("Apellidos:");

        lblCedula.setText("Cédula:");

        lblEdad.setText("Edad:");

        lblTelefono.setText("Télefono:");

        lblCorreo.setText("Correo electrónico:");

        lblTipoPro.setText("Tipo de propiedad:");

        rbtnUrbano.setText("Urbano");

        rbtnRural.setText("Rural");

        lblDireccion.setText("Dirección de propiedad:");

        lblValorComercial.setText("Valor comercial:");

        lblValorEdificacion.setText("Valor de edificación: ");

        lblAreatotal.setText("Área total:");

        lblAreaConstruccion.setText("Área de construcción:");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblCodCastral.setText("Codigo castral:");

        lblValorTerreno.setText("Valor de terreno: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblEdad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblApellidos)
                                    .addComponent(lblNombres))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAreaConstruccion)
                                        .addGap(21, 21, 21)
                                        .addComponent(txtAreaConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCodCastral)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCodCastral, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTipoPro)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDireccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAreatotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnUrbano)
                                    .addComponent(rbtnRural))))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblValorEdificacion)
                                .addGap(18, 18, 18)
                                .addComponent(txtValorEdificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblValorTerreno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblValorComercial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCodCastral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodCastral))
                                .addGap(130, 130, 130))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblValorTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblValorEdificacion)
                                    .addComponent(txtValorEdificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnUrbano))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblValorComercial)
                                            .addComponent(txtValorComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Guardar)
                                            .addComponent(rbtnRural))
                                        .addGap(17, 17, 17)))))
                        .addGap(8, 8, 8)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCedula)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNombres)
                                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lblTipoPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblApellidos)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAreatotal)
                            .addComponent(txtAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAreaConstruccion)
                    .addComponent(txtAreaConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Gestión Propiedades");
        lblTitulo.setToolTipText("");

        tblPropiedadPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPropiedadPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPropiedadProMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPropiedadPro);

        lblBuscar.setText("Buscar por número de cédula:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscar)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(656, 656, 656)
                        .addComponent(lblTitulo)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // Verificar qué tipo de propiedad está seleccionada
        String tipoPropiedad;
        if (rbtnRural.isSelected()) {
            tipoPropiedad = "Rural";
        } else if (rbtnUrbano.isSelected()) {
            tipoPropiedad = "Urbano";
        } else {
            // Si no se ha seleccionado ningún tipo de propiedad, mostrar un mensaje de error y salir del método
            JOptionPane.showMessageDialog(null, "Por favor, seleccione el tipo de propiedad.");
            return;
        }

        // Crear una instancia de PersonaYDatosPredialesModelo con los datos ingresados en los campos de texto y los botones de radio
        PersonaYDatosPredialesModelo pM = new PersonaYDatosPredialesModelo(
                0, // ID autogenerado en la base de datos
                txtNombres.getText(),
                txtApellidos.getText(),
                txtCedula.getText(),
                txtCorreo.getText(),
                txtTelefono.getText(),
                Integer.parseInt(txtEdad.getText()),
                0, // ID_PRED inicializado en 0, puede ser autogenerado
                0, // ID_PERSONA_PER inicializado en 0, puede ser autogenerado
                txtCodCastral.getText(),
                tipoPropiedad, // Usar el tipo de propiedad obtenido de los botones de radio
                txtDireccion.getText(),
                Double.parseDouble(txtAreaTotal.getText()),
                Double.parseDouble(txtAreaConstruccion.getText()),
                Double.parseDouble(txtValorTerreno.getText()),
                Double.parseDouble(txtValorEdificacion.getText()),
                Double.parseDouble(txtValorComercial.getText())
        );

        PersonaYDatosPredialesControlador pC = new PersonaYDatosPredialesControlador();
        pC.crearPersona(pM);
        listaPersonayDatosPredialesModelo.add(pM);
        setDatos();
        limpiarTabla();
        cargarTabla();


    }//GEN-LAST:event_GuardarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarTabla();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCedula.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtEdad.setText("");
        txtCodCastral.setText("");
        txtDireccion.setText("");
        txtAreaTotal.setText("");
        txtAreaConstruccion.setText("");
        txtValorTerreno.setText("");
        txtValorEdificacion.setText("");
        txtValorComercial.setText("");

        // Limpia la selección de los botones de radio
        rbtnRural.setSelected(false);
        rbtnUrbano.setSelected(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cedula = txtBuscar.getText(); // Obtener la cédula desde el campo de texto
        PersonaYDatosPredialesControlador controlador = new PersonaYDatosPredialesControlador();
        ArrayList<Object[]> listaFilas = controlador.buscarPersonaYDatosPrediales(cedula);

        if (listaFilas != null) {
            limpiarTabla(); // Limpiar la tabla antes de mostrar nuevos resultados

            // Añadir las filas obtenidas a la tabla
            for (Object[] fila : listaFilas) {
                modelo.addRow(fila);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron resultados para la cédula proporcionada.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        limpiarTabla();
        cargarTabla();
    }//GEN-LAST:event_formMouseClicked

    private void tblPropiedadProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPropiedadProMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) tblPropiedadPro.getModel();
        int filaSeleccionada = tblPropiedadPro.getSelectedRow();
        if (filaSeleccionada != -1) { // Verifica si se ha seleccionado una fila válida
            // Obtener los datos de la fila seleccionada y establecerlos en los campos correspondientes
            txtCedula.setText((String) dtm.getValueAt(filaSeleccionada, 1));
            txtNombres.setText((String) dtm.getValueAt(filaSeleccionada, 2));
            txtApellidos.setText((String) dtm.getValueAt(filaSeleccionada, 3));
            txtCorreo.setText((String) dtm.getValueAt(filaSeleccionada, 4));
            txtTelefono.setText((String) dtm.getValueAt(filaSeleccionada, 5));
            txtEdad.setText(String.valueOf(dtm.getValueAt(filaSeleccionada, 6)));
            txtCodCastral.setText((String) dtm.getValueAt(filaSeleccionada, 7));
            txtDireccion.setText((String) dtm.getValueAt(filaSeleccionada, 8));
            txtAreaTotal.setText(String.valueOf(dtm.getValueAt(filaSeleccionada, 9)));
            txtAreaConstruccion.setText(String.valueOf(dtm.getValueAt(filaSeleccionada, 10)));
            txtValorTerreno.setText(String.valueOf(dtm.getValueAt(filaSeleccionada, 11)));
            txtValorEdificacion.setText(String.valueOf(dtm.getValueAt(filaSeleccionada, 12)));
            txtValorComercial.setText(String.valueOf(dtm.getValueAt(filaSeleccionada, 13)));

            // Establecer la selección de los botones de radio según el tipo de propiedad
            String tipoPropiedad = ((String) dtm.getValueAt(filaSeleccionada, 8)).trim(); // Obtener el tipo de propiedad de la fila seleccionada
            System.out.println("Tipo de propiedad obtenido de la fila: " + tipoPropiedad);
            if (tipoPropiedad.equalsIgnoreCase("Rural")) {
                System.out.println("Seleccionando Rural");
                rbtnRural.setSelected(true);
                rbtnUrbano.setSelected(false);
            } else if (tipoPropiedad.equalsIgnoreCase("Urbano")) {
                System.out.println("Seleccionando Urbano");
                rbtnRural.setSelected(false);
                rbtnUrbano.setSelected(true);
            } else {
                System.out.println("Tipo de propiedad no reconocido: " + tipoPropiedad);
            }
        }
    }//GEN-LAST:event_tblPropiedadProMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        PersonaYDatosPredialesModelo pM = new PersonaYDatosPredialesModelo(
                0, // ID autogenerado en la base de datos
                txtNombres.getText(),
                txtApellidos.getText(),
                txtCedula.getText(),
                txtCorreo.getText(),
                txtTelefono.getText(),
                Integer.parseInt(txtEdad.getText()),
                0, // ID_PRED inicializado en 0, puede ser autogenerado
                0, // ID_PERSONA_PER inicializado en 0, puede ser autogenerado
                txtCodCastral.getText(),
                (rbtnRural.isSelected() ? "Rural" : (rbtnUrbano.isSelected() ? "Urbano" : "")), // Usar el tipo de propiedad obtenido de los botones de radio
                txtDireccion.getText(),
                Double.parseDouble(txtAreaTotal.getText()),
                Double.parseDouble(txtAreaConstruccion.getText()),
                Double.parseDouble(txtValorTerreno.getText()),
                Double.parseDouble(txtValorEdificacion.getText()),
                Double.parseDouble(txtValorComercial.getText())
        );
        PersonaYDatosPredialesControlador pC = new PersonaYDatosPredialesControlador();
        pC.actualizarPersonaYDatosPrediales(pM);
        limpiarTabla();
        cargarTabla();


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String cedula = txtCedula.getText(); // Obtener la cédula desde el campo de texto
        PersonaYDatosPredialesControlador pC = new PersonaYDatosPredialesControlador();
        pC.eliminarPersonaYDatosPrediales(cedula);
        limpiarTabla();
        cargarTabla();
        limpiarEntradas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void limpiarTabla() {
        int a = modelo.getRowCount() - 1;  //Índices van de 0 a n-1
        //System.out.println("Tabla "+a);   //Para mostrar por consola el resultado
        for (int i = a; i >= 0; i--) {

            //System.out.println("i "+i);    //Para mostrar por consola el resultado
            modelo.removeRow(i);
        }
    }

    private void cargarTabla() {
        PersonaYDatosPredialesControlador pC = new PersonaYDatosPredialesControlador();
        ArrayList<Object[]> lista = pC.datosPersonasYPrediales();
        for (Object[] filas : lista) {
            modelo.addRow(filas);
        }

        tblPropiedadPro.setModel(modelo);

    }

    public void limpiarEntradas() {
        txtCedula.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtEdad.setText("");
        txtCodCastral.setText("");
        txtDireccion.setText("");
        txtAreaTotal.setText("");
        txtAreaConstruccion.setText("");
        txtValorTerreno.setText("");
        txtValorEdificacion.setText("");
        txtValorComercial.setText("");

        // Limpia la selección de los botones de radio
        rbtnRural.setSelected(false);
        rbtnUrbano.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblAreaConstruccion;
    private javax.swing.JLabel lblAreatotal;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodCastral;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoPro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorComercial;
    private javax.swing.JLabel lblValorEdificacion;
    private javax.swing.JLabel lblValorTerreno;
    private javax.swing.JRadioButton rbtnRural;
    private javax.swing.JRadioButton rbtnUrbano;
    private javax.swing.JTable tblPropiedadPro;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtAreaConstruccion;
    private javax.swing.JTextField txtAreaTotal;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodCastral;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValorComercial;
    private javax.swing.JTextField txtValorEdificacion;
    private javax.swing.JTextField txtValorTerreno;
    // End of variables declaration//GEN-END:variables
}
