/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DIU.Vista;

import DIU.Controlador.ConsultaPagosControlador;
import DIU.Controlador.DatosPredialesControlador;
import DIU.Controlador.PersonaControlador;
import DIU.Controlador.PlantillaPDFConsultaPagosControlador;
import DIU.Modelo.ConsultaPagosModelo;
import DIU.Modelo.DatosPredialesModelo;
import DIU.Modelo.PersonaModelo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaConsulta1 extends javax.swing.JFrame {

    public String codCastralPred, fecha_ingreso_pago, fecha_vencimiento_pago, descripcion_pago, direccion, sub_total_pago;
    DefaultTableModel modelo = new DefaultTableModel();
    private String cedula;

    public List<PersonaModelo> personas;
    public List<ConsultaPagosModelo> consultas;
    public List<DatosPredialesModelo> predios;

    /**
     * Creates new form VentanaConsulta1
     */
    public VentanaConsulta1(String cedula) {
        initComponents();
        setModelo();
        this.cedula = cedula;
        lblCedula.setText(cedula);
        lblFecha.setText(fechaString);
    }

    // Declarar una instancia de PlantillaPDFConsultaPagosControlador
    PlantillaPDFConsultaPagosControlador controladorPDF = new PlantillaPDFConsultaPagosControlador();
    // Declarar una instancia de ConsultaPagosControlador
    ConsultaPagosControlador controladorConsulta = new ConsultaPagosControlador();
    // Declarar una instancia de DatosPredialesControlador
    DatosPredialesControlador controladorPrediales = new DatosPredialesControlador();
    // Declarar una instancia de PersonaControlador
    PersonaControlador controladorPersona = new PersonaControlador();

    // Obtener la fecha actual
    Date fechaActual = new Date();

    // Formatear la fecha a un String
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    String fechaString = formato.format(fechaActual);

    public void setModelo() {
        String[] cabecera = {"Nro.", "COD Castral", "Fecha de ingreso", "Fecha de vencimiento",
            "Comentario", "Dirección", "Subtotal"};
        modelo.setColumnIdentifiers(cabecera);
        tblConsultaPredios.setModel(modelo);
    }

    public void setDatosPago(ArrayList<Object[]> datosPago) {
        // Limpiar la tabla antes de agregar nuevos datos
        modelo.setRowCount(0);

        // Agregar los datos a la tabla
        int contador = 1; // Inicializar el contador
        for (Object[] fila : datosPago) {
            Object[] nuevaFila = new Object[7];
            nuevaFila[0] = contador;
            System.arraycopy(fila, 0, nuevaFila, 1, fila.length);
            modelo.addRow(nuevaFila);
            contador++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        btnVerDatosPrediales = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultaPredios = new javax.swing.JTable();
        btnCalcularPago = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTitulo.setText("Consulta Predios de:");

        btnVerDatosPrediales.setText("Ver datos prediales");
        btnVerDatosPrediales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatosPredialesActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblConsultaPredios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConsultaPredios);

        btnCalcularPago.setText("Calcular Pago");

        lblFecha.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lblTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVerDatosPrediales, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(331, 331, 331)
                                .addComponent(btnCalcularPago, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDatosPrediales)
                    .addComponent(btnImprimir)
                    .addComponent(btnSalir)
                    .addComponent(btnCalcularPago))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDatosPredialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatosPredialesActionPerformed
        ConsultaPagosControlador controlador = new ConsultaPagosControlador();
        ArrayList<Object[]> datosPrediales = controlador.verDatosPrediales(cedula);

        // Crear la nueva ventana y pasar los datos
        VentanaConsulta2 v2 = new VentanaConsulta2(cedula);
        v2.setDatos(datosPrediales);
        v2.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnVerDatosPredialesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        PantallaPrincipal pantallaPrin = new PantallaPrincipal();
        pantallaPrin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // Poblar las listas personas, consultas y predios con los datos que quieres incluir en el PDF
        // Crear una nueva lista de personas y agregar la persona recuperada a la lista
        controladorPDF.personas = new ArrayList<>();
        controladorPDF.personas.add(controladorPersona.recuperarDatosPersona(cedula));

        // Obtener los datos de pago del controlador
        ArrayList<Object[]> datosPago = controladorConsulta.consultaPago(cedula);
        controladorPDF.consultas = new ArrayList<>();
        for (Object[] fila : datosPago) {
            ConsultaPagosModelo consulta = new ConsultaPagosModelo();
            // Aquí debes asignar los valores de fila a los campos correspondientes en consulta
            controladorPDF.consultas.add(consulta);
        }

        DatosPredialesControlador pC = new DatosPredialesControlador();
        ArrayList<Object[]> listaFilas = pC.buscarPropiedadesPorCedula(cedula);
        controladorPDF.predios = new ArrayList<>();
        for (Object[] fila : listaFilas) {
            DatosPredialesModelo predio = new DatosPredialesModelo();
            // Aquí debes asignar los valores de fila a los campos correspondientes en predio
            controladorPDF.predios.add(predio);
        }

        // Llamar al método crearPDF cuando se haga clic en el botón btnImprimir
        controladorPDF.crearPDF("C:\\Users\\Usuario\\OneDrive\\Escritorio\\PDF ConsultaPagos.pdf");
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularPago;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerDatosPrediales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblConsultaPredios;
    // End of variables declaration//GEN-END:variables
}
