CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_ActualizarDatosPrediales`(
    IN p_CEDULA_PER VARCHAR(10),
    IN p_COD_CASTRAL_PRED VARCHAR(45),
    IN p_TIPO_PRED VARCHAR(15),
    IN p_DIRECCION_PRED VARCHAR(100),
    IN p_AREA_TOTAL_PRED DOUBLE,
    IN p_AREA_CONSTRUCCION_PRED DOUBLE,
    IN p_VALOR_TERRENO_PRED DOUBLE,
    IN p_VALOR_EDIFICACION_PRED DOUBLE
)
BEGIN
    -- Declarar variable para el valor comercial
    DECLARE p_VALOR_COMERCIAL_PRED DOUBLE;

    -- Calcular el valor comercial como la suma del valor del terreno y la edificación
    SET p_VALOR_COMERCIAL_PRED = p_VALOR_TERRENO_PRED + p_VALOR_EDIFICACION_PRED;

    -- Actualizar los datos prediales asociados a la persona
    UPDATE DATOSPREDIALES
    INNER JOIN PERSONA ON DATOSPREDIALES.ID_PER = PERSONA.ID_PER
    SET 
        TIPO_PRED = p_TIPO_PRED,
        DIRECCION_PRED = p_DIRECCION_PRED,
        AREA_TOTAL_PRED = p_AREA_TOTAL_PRED,
        AREA_CONSTRUCCION_PRED = p_AREA_CONSTRUCCION_PRED,
        VALOR_TERRENO_PRED = p_VALOR_TERRENO_PRED,
        VALOR_EDIFICACION_PRED = p_VALOR_EDIFICACION_PRED,
        VALOR_COMERCIAL_PRED = p_VALOR_COMERCIAL_PRED
    WHERE PERSONA.CEDULA_PER = p_CEDULA_PER AND DATOSPREDIALES.COD_CASTRAL_PRED = p_COD_CASTRAL_PRED;
END