CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_ConsultaPagos`(
    IN p_CEDULA_PER varchar(10)
)
BEGIN
    SELECT 
        DATOSPREDIALES.COD_CASTRAL_PRED,
        CONSULTAPAGOS.FECHA_INGRESO_PAGO,
        CONSULTAPAGOS.FECHA_VENCIMIENTO_PAGO,
        CONSULTAPAGOS.DESCRIPCION_PAGO,
        DATOSPREDIALES.DIRECCION_PRED,
        CONSULTAPAGOS.SUB_TOTAL_PAGO
    FROM CONSULTAPAGOS
    INNER JOIN DATOSPREDIALES ON CONSULTAPAGOS.ID_PRED = DATOSPREDIALES.ID_PRED
    INNER JOIN PERSONA ON DATOSPREDIALES.ID_PER = PERSONA.ID_PER
    WHERE PERSONA.CEDULA_PER = p_CEDULA_PER;
END